### PR TITLE
Create CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by mukireus**

### CODE REVIEW

**Comment by mukireus** [comment]
@all-contributors please add <Adem68> for <code> <maintenance>

**Comment by mukireus** [comment]
@all-contributors please add <Adem68> for <maintenance>

**Comment by mukireus** [comment]
@all-contributors please add @Adem68 for maintenance

**Comment by mukireus** [comment]
@all-contributors please add @mukireus for design, code

**Comment by mukireus** [comment]
@all-contributors please add @Wijt for maintenance

**Comment by mukireus** [comment]
@all-contributors please add @Wijt for maintenance

**Comment by Adem68** [comment]
[**@all-contributors**](https://github.com/all-contributors) please add [**@Adem68**](https://github.com/mukireus) for design, code

**Comment by Adem68** [comment]
@all-contributors please add @Adem68 for code

**Comment by Adem68** [comment]
@all-contributors please add @Adem68 for design

**Comment by Adem68** [comment]
[**@all-contributors**](https://github.com/all-contributors) please add [**@mukireus**](https://github.com/Wijt) for maintenance

**Comment by Adem68** [comment]
[**@all-contributors**](https://github.com/all-contributors) please add [**@mukireus**](https://github.com/Adem68) for design

**Comment by Adem68** [comment]
@all-contributors please add @mukireus for maintenance

**Comment by Adem68** [comment]
@all-contributors please add @Wijt for design, code

**Pull request merged**
